apiVersion: v1
kind: Service
metadata:
  name: myangular-app-service
spec:
  selector:
    app: myangular-app-service
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myangular-app-service
spec:
  selector:
    matchLabels:
      app: myangular-app-service
  replicas: 1
  template:
    metadata:
      labels:
        app: myangular-app-service
    spec:
      containers:
      - name: myangular-app-service
        image: chan29/angularfrontend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80